### ISSUE TITLE
Error in elevator model

### ISSUE THREAD

**Issue by DarkenedDragon** [calcmogul/state-space-guide#1]
I noticed when you were writing the equations of motion for an elevator, you mistakenly substituted the resistance instead of the radius for the angular velocity of the motor armature on page 126 of the state space guide (See pictures for details). 

![state_space](https://user-images.githubusercontent.com/24358893/47620570-df052600-dac1-11e8-9431-80a545ff0976.png)

**Comment by calcmogul** [comment]
Good catch. I need to come up with a good way of building draft PDFs in CI or something so PRs can actually get review from the issue filer before being merged; LaTeX isn't the most readable thing.
